In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[[1 '21st century classical' 0.9793333333333332 ... 75.3365
  0.1037833333333333 27.83333333333333]
 [1 '432hz' 0.49478 ... 120.28566666666666 0.22175 52.5]
 [1 '8-bit' 0.762 ... 133.444 0.975 48.0]
 ...
 [1 'zouk' 0.2632611111111112 ... 101.9652222222222 0.8241111111111111
  46.66666666666666]
 [0 'zurich indie' 0.993 ... 91.278 0.7390000000000001 0.0]
 [1 'zydeco' 0.4210384920634921 ... 126.36608730158731 0.8085436507936509
  30.26190476190477]]


In [5]:
print(y)


[6 5 7 ... 5 7 7]


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

ValueError: ignored

In [7]:
print(x)

[[1 '21st century classical' 0.9793333333333332 ... 75.3365
  0.1037833333333333 27.83333333333333]
 [1 '432hz' 0.49478 ... 120.28566666666666 0.22175 52.5]
 [1 '8-bit' 0.762 ... 133.444 0.975 48.0]
 ...
 [1 'zouk' 0.2632611111111112 ... 101.9652222222222 0.8241111111111111
  46.66666666666666]
 [0 'zurich indie' 0.993 ... 91.278 0.7390000000000001 0.0]
 [1 'zydeco' 0.4210384920634921 ... 126.36608730158731 0.8085436507936509
  30.26190476190477]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[0.0 1.0 '21st century classical' ... 75.3365 0.1037833333333333
  27.83333333333333]
 [0.0 1.0 '432hz' ... 120.28566666666666 0.22175 52.5]
 [0.0 1.0 '8-bit' ... 133.444 0.975 48.0]
 ...
 [0.0 1.0 'zouk' ... 101.9652222222222 0.8241111111111111
  46.66666666666666]
 [1.0 0.0 'zurich indie' ... 91.278 0.7390000000000001 0.0]
 [0.0 1.0 'zydeco' ... 126.36608730158731 0.8085436507936509
  30.26190476190477]]


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[6 5 7 ... 5 7 7]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [13]:
print(x_train)

[[0.0 1.0 'chattanooga indie' ... 90.02600000000002 0.7490000000000001
  49.0]
 [1.0 0.0 'arkansas hip hop' ... 149.661 0.3738333333333334
  64.83333333333333]
 [0.0 1.0 "british children's music" ... 98.98 0.8109999999999999 53.0]
 ...
 [0.0 1.0 'french opera' ... 104.83025631919432 0.2548056102440976
  7.898541211356338]
 [0.0 1.0 'bass music' ... 133.94493749999998 0.34908125 50.1875]
 [0.0 1.0 'folk rock italiano' ... 118.41497 0.6335200000000001 52.09]]


In [14]:
print(x_test)

[[0.0 1.0 'north carolina indie' ... 118.59472352941178
  0.3206670588235294 48.08235294117648]
 [0.0 1.0 'romantico' ... 116.67451234567903 0.6190432098765432
  33.59876543209876]
 [0.0 1.0 'orquesta tipica' ... 137.68318658008658 0.7117281385281385
  3.6025974025974024]
 ...
 [0.0 1.0 'socal pop punk' ... 132.27985287894307 0.5494029176516834
  47.14628163577034]
 [0.0 1.0 'birmingham metal' ... 126.4525332875458 0.3516306886446886
  37.08631868131869]
 [0.0 1.0 'nz hardcore' ... 141.118 0.593 49.0]]


In [15]:
print(y_train)

[7 7 8 ... 2 6 9]


In [16]:
print(y_test)

[ 9  5  5  8  7  5  0  1  7  7  7  9  9  4  7 11 10 11  9  4  7  1  7  0
  7  4  2  7 11  9  9  3 10 11  6 11 11  5  6  1 11  5  7  6  9  4  0  2
  1  3  5  2  7  5  7  8  7 11 11  9  2 11 10  9  7  2  2  7  5  2  2  9
  9  8 11  1  1  1  4  7  7  5  9 10  8  1  2  2  2 11  6  5  2  1 11 11
  9  9  0 11  8  5  7  2  4 11  9  9  1  0  9  7  7 10  0  6  5 11  7  5
  9  5  9  7  2  5  1  9  7 10  7  7  0  9  3 10 10 11  9  7  7  7  7  3
  7  0  6  7 11  9  7 11  6  7  2  2 11  7  1  5  3  7  7  3  7  1  7  5
  7  7  6  7 11  6  5  0  7  9  2  6 10 11  7  0  7  7  2  9  1  1  2  7
 11  7  1 11 11 10  3  6  7  4  7 11  0  5  2  3  7  2 10 11 11  5  5  0
  7 10 10  2 10  4 11 10  2  6  5 10  9  9  2 11  7  4  0  8  9 11  4  9
  9  3  2  8  9 10 11  9  0  9  7  6  7  8  7  7  9 10  9  4 11  7  7  7
 10 11  7  9  7  5  2  0  9  2  0  7  7  7  9  7  5  5  7  5  7 11  1  6
 10  4  7  4  3  2 11 11  7  7  9  7 10  9  1  7  9  9  7  7  5  5  9  9
  6  0  6  0  7  2  1  8 11 11 11  4  5  7  5  3  3

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[0.0 1.0 'chattanooga indie' ... -1.6732634537480016 1.2780592983329702
  0.5390210244213054]
 [1.0 0.0 'arkansas hip hop' ... 1.7650570339027283 -0.5802020019457286
  1.482124881293646]
 [0.0 1.0 "british children's music" ... -1.157010889877379
  1.5851553461800043 0.7772788408943179]
 ...
 [0.0 1.0 'french opera' ... -0.8197080281301841 -1.1697656042833995
  -1.9091649317881312]
 [0.0 1.0 'bass music' ... 0.8589304357816678 -0.7028030820690697
  0.609753813686731]
 [0.0 1.0 'folk rock italiano' ... -0.03646665364232733 0.706068143407557
  0.7230751876467078]]


In [19]:
print(x_test)

[[0.0 1.0 'north carolina indie' ... -0.026102769297495207
  -0.8435431758281698 0.48436187828926197]
 [0.0 1.0 'romantico' ... -0.13681462397418448 0.6343622557878053
  -0.3783451053629019]
 [0.0 1.0 'orquesta tipica' ... 1.0744632336353321 1.0934457281086014
  -2.1650504796795462]
 ...
 [0.0 1.0 'socal pop punk' ... 0.7629281792837704 0.2894226023496271
  0.42860530196698476]
 [0.0 1.0 'birmingham metal' ... 0.4269477594097078 -0.6901752992946766
  -0.17061089986477693]
 [0.0 1.0 'nz hardcore' ... 1.2725011199931078 0.5053660166533329
  0.5390210244213054]]
